<?php

/**
 * @file
 * Contains hook implementations for login_redirect module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function login_redirect_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#submit'][] = 'login_redirect_user_redirect';
  }
}

/**
 * Redirects the user to the specified URL after they login.
 */
function login_redirect_user_redirect(&$form, FormStateInterface $form_state) {
  $user_roles = \Drupal::currentUser()->getRoles();
  if (in_array('reporter', $user_roles)) {
    $url = Url::fromRoute('/reporter-dashboard');
    $form_state->setRedirectUrl($url);
  }
  elseif (in_array('editor', $user_roles)) {
    $url = Url::fromRoute('/editor-dashboard');
    $form_state->setRedirectUrl($url);
  }
}
